"""initial database

Revision ID: d4b7bf58a70b
Revises: 
Create Date: 2026-05-23 13:14:35.062416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b7bf58a70b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandes_frequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('frequence_debut', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('frequence_fin', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=False),
    sa.Column('usage_service', sa.String(length=150), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_locked', sa.Boolean(), nullable=False),
    sa.Column('statut_compte', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('valide_par_id', sa.Integer(), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['valide_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('demandes_autorisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('bande_id', sa.Integer(), nullable=True),
    sa.Column('objet', sa.String(length=255), nullable=False),
    sa.Column('type_demande', sa.String(length=100), nullable=True),
    sa.Column('service_concerne', sa.String(length=150), nullable=True),
    sa.Column('frequence_min', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('frequence_max', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('zone_utilisation', sa.String(length=255), nullable=True),
    sa.Column('puissance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date_debut_souhaitee', sa.Date(), nullable=True),
    sa.Column('date_fin_souhaitee', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_soumission', sa.DateTime(), nullable=True),
    sa.Column('date_derniere_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bande_id'], ['bandes_frequence.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demandes_autorisation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demandes_autorisation_reference'), ['reference'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lue', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_lecture', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profils_utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_utilisateur', sa.String(length=50), nullable=False),
    sa.Column('raison_sociale', sa.String(length=255), nullable=False),
    sa.Column('identifiant', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('secteur_activite', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('autorisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('bande_id', sa.Integer(), nullable=True),
    sa.Column('creee_par_id', sa.Integer(), nullable=True),
    sa.Column('numero_autorisation', sa.String(length=100), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('document_url', sa.String(length=255), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bande_id'], ['bandes_frequence.id'], ),
    sa.ForeignKeyConstraint(['creee_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_autorisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demande_id')
    )
    with op.batch_alter_table('autorisations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autorisations_numero_autorisation'), ['numero_autorisation'], unique=True)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('type_decision', sa.String(length=50), nullable=False),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('date_decision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_autorisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demande_id')
    )
    op.create_table('historique_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('demande_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entite', sa.String(length=100), nullable=True),
    sa.Column('entite_id', sa.Integer(), nullable=True),
    sa.Column('ancien_statut', sa.String(length=50), nullable=True),
    sa.Column('nouveau_statut', sa.String(length=50), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_autorisation.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('type_observation', sa.String(length=50), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date_observation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_autorisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pieces_jointes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demande_id', sa.Integer(), nullable=False),
    sa.Column('ajoutee_par_id', sa.Integer(), nullable=True),
    sa.Column('nom_original', sa.String(length=255), nullable=False),
    sa.Column('nom_stockage', sa.String(length=255), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=True),
    sa.Column('chemin', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('taille_octets', sa.Integer(), nullable=True),
    sa.Column('date_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ajoutee_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['demande_id'], ['demandes_autorisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pieces_jointes')
    op.drop_table('observations')
    op.drop_table('historique_actions')
    op.drop_table('decisions')
    with op.batch_alter_table('autorisations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autorisations_numero_autorisation'))

    op.drop_table('autorisations')
    op.drop_table('profils_utilisateurs')
    op.drop_table('notifications')
    with op.batch_alter_table('demandes_autorisation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demandes_autorisation_reference'))

    op.drop_table('demandes_autorisation')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('bandes_frequence')
    # ### end Alembic commands ###
